spring.application.name=easydateapp
# ==========================================
# CONFIGURACIÓN DE DATA SOURCE (SQL SERVER)
# ==========================================
# Cambiamos 'master' por 'EasyDatesDB' y usamos barras normales (/) para la instancia SQLEXPRESS
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=EasyDatesDB;encrypt=true;trustServerCertificate=true;

# Tu usuario administrador de SQL Server
spring.datasource.username=sa

# ¡IMPORTANTE! Coloca aquí la contraseña real de tu usuario 'sa'
spring.datasource.password=1234

# Driver oficial de Microsoft para SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
# Dialecto para que Hibernate optimice las consultas a SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Mantiene tu base de datos tal cual está (no creará ni borrará tablas automáticamente)
spring.jpa.hibernate.ddl-auto=none

# Muestra las consultas SQL en la consola del IDE (buenísimo para ver qué hace tu login)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true